apiVersion: v1
kind: ConfigMap
metadata:
  name: init-script
data:
  init.sql: |
    CREATE TABLE users (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100) NOT NULL
    );
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-app
spec:
  replicas: 8
  selector:
    matchLabels:
      app: app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      volumes:
        - name: init-script
          configMap:
            name: init-script
      containers:
        - name: db-app
          image: mikhailgon/app:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              value: "localhost"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "mypassword"
            - name: DATABASE_NAME
              value: "testdb"
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "mypassword"
            - name: POSTGRES_DB
              value: "testdb"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/
---
apiVersion: v1
kind: Service
metadata:
  name: db-app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: db-app-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: db-app
  minReplicas: 4
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60